# Generated by Django 2.2 on 2019-04-10 02:14

from django.db import migrations, models
import django.db.models.deletion
import exams.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('idDiscipline', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100, verbose_name='Full name')),
                ('students', models.ManyToManyField(to='core.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='core.Teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idQuestion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headQuestion', models.CharField(max_length=500, verbose_name='Head Question')),
                ('typeQuestion', models.CharField(choices=[('CODE', 'Code'), ('SUBJECTIVE', 'Subjective'), ('OBJECTIVE', 'Objective')], default='OBJECTIVE', max_length=45, verbose_name='Type Question')),
                ('discipline', models.ForeignKey(on_delete='Discipline', related_name='questions', to='exams.Discipline', verbose_name='discipline')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('idTest', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aplicationDate', models.DateTimeField(verbose_name='Aplication Date')),
                ('aplicationDateLimit', models.DateTimeField(verbose_name='Aplication Date Limit')),
                ('name', models.TextField(max_length=254, verbose_name='Text name')),
                ('discipline', models.ForeignKey(on_delete=exams.models.Discipline, related_name='tests', to='exams.Discipline', verbose_name='discipline')),
                ('questions', models.ManyToManyField(to='exams.Question')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TestStudent',
            fields=[
                ('idTestStudent', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scores', models.FloatField(verbose_name='scores')),
                ('timeStart', models.DateTimeField(verbose_name='Time Start')),
                ('timeFinish', models.DateTimeField(verbose_name='Time Finish')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testStudents', to='core.Student', verbose_name='student')),
                ('test', models.ForeignKey(on_delete=exams.models.Test, related_name='testStudents', to='exams.Test', verbose_name='test')),
            ],
            options={
                'verbose_name': 'TestStudent',
                'verbose_name_plural': 'TestStudents',
            },
        ),
        migrations.CreateModel(
            name='CodeAnswer',
            fields=[
                ('idCodeAnswer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inputCode', models.TextField(max_length=1000, verbose_name='Input Code')),
                ('outputCode', models.TextField(max_length=1000, verbose_name='Output Code')),
                ('question', models.ForeignKey(on_delete=exams.models.Question, related_name='CodeAnswers', to='exams.Question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'CodeAnswer',
                'verbose_name_plural': 'CodeAnswers',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('idChoice', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correct', models.BooleanField(default=False)),
                ('textChoice', models.TextField(max_length=100, verbose_name='Text Choice')),
                ('question', models.ForeignKey(on_delete=exams.models.Question, related_name='choices', to='exams.Question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('idAnswer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('textAnswer', models.TextField(max_length=500, verbose_name='Text Answer')),
                ('correct', models.BooleanField(default=False, verbose_name='correct')),
                ('choice', models.ForeignKey(on_delete=exams.models.Choice, related_name='answers', to='exams.Choice', verbose_name='choice')),
                ('question', models.ForeignKey(on_delete=exams.models.Question, related_name='answers', to='exams.Question', verbose_name='question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.Student', verbose_name='student')),
                ('test', models.ForeignKey(on_delete=exams.models.Test, related_name='answers', to='exams.Test', verbose_name='test')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
